import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "@/components/ui/toaster";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import HydrationHandler from "@/components/HydrationHandler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <HydrationHandler>
      <NextAuthSessionProvider>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
          <Toaster />
        </ReduxProvider>
      </NextAuthSessionProvider>
    </HydrationHandler>
  );
}